name: Deploy
on:
  push:
    branches:
      - "master"
jobs:
  docs:
    name: coder.com/docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mono
        uses: actions/checkout@v2
        with:
          repository: cdr/m
          ref: refs/heads/master
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: true
          fetch-depth: 0
      - name: Checkout Docs
        run: git fetch && git checkout ${GITHUB_SHA}
        working-directory: ./product/coder.com/site/docs
      - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "cdr/docs: bump product/coder.com/site/docs ${GITHUB_SHA}" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: cdr/m
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          branch: master
