name: Deploy (Preview)
on:
  push:
    branches:
      - "**"
      - "!master"
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mono
        uses: actions/checkout@v2
        with:
          repository: cdr/m
          ref: refs/heads/master
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: true
          fetch-depth: 0
      - name: Checkout Docs
        run: git fetch && git checkout ${GITHUB_SHA}
        working-directory: ./product/coder.com/site/docs
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Deploy
        run: ./product/coder.com/site/docs/.github/ci/deploy.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_tGkWfhEGGelkkqUUm9nXq17r
          VERCEL_PROJECT_ID: QmZRucMRh3GFk1817ZgXjRVuw5fhTspHPHKct3JNQDEPGd
